version: '0'
services:
  neodb:
    image: 'neo4j:3.3.0'
    environment:
    - NEO4J_dbms_memory_heap_initial__size=3G
    - NEO4J_dbms_memory_heap_max__size=3G
    ports:
    - '7474:7474'
    - '7687:7687'
    volumes:
    - ./plugins:/var/lib/neo4j/plugins
    - ./conf:/var/lib/neo4j/conf
